// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recebi.Api.Infra;

#nullable disable

namespace Recebi.Api.Migrations
{
    [DbContext(typeof(RecebiContext))]
    partial class RecebiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Recebi.Api.Domain.Encomenda", b =>
                {
                    b.Property<int>("IdEncomenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_encomenda");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEncomenda"));

                    b.Property<string>("Apartamento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("apartamento");

                    b.Property<string>("CodigoRastreio")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo_rastreio");

                    b.Property<DateTime?>("DataEntrada")
                        .HasColumnType("datetime")
                        .HasColumnName("data_entrada");

                    b.Property<DateTime?>("DataRetirada")
                        .HasColumnType("datetime")
                        .HasColumnName("data_retirada");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pendente")
                        .HasColumnName("status");

                    b.HasKey("IdEncomenda");

                    b.HasIndex("IdUsuario");

                    b.ToTable("encomendas", (string)null);
                });

            modelBuilder.Entity("Recebi.Api.Domain.Historico", b =>
                {
                    b.Property<int>("IdHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historico");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdHistorico"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("acao");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime")
                        .HasColumnName("data_hora");

                    b.Property<string>("Detalhes")
                        .HasColumnType("longtext")
                        .HasColumnName("detalhes");

                    b.Property<int?>("IdEncomenda")
                        .HasColumnType("int")
                        .HasColumnName("id_encomenda");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo");

                    b.HasKey("IdHistorico");

                    b.HasIndex("IdEncomenda");

                    b.HasIndex("IdUsuario");

                    b.ToTable("historico", (string)null);
                });

            modelBuilder.Entity("Recebi.Api.Domain.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apartamento")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("apart");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senha");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefone");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuarios", (string)null);

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Recebi.Api.Domain.Morador", b =>
                {
                    b.HasBaseType("Recebi.Api.Domain.Usuario");

                    b.HasDiscriminator().HasValue("Morador");
                });

            modelBuilder.Entity("Recebi.Api.Domain.Porteiro", b =>
                {
                    b.HasBaseType("Recebi.Api.Domain.Usuario");

                    b.HasDiscriminator().HasValue("Porteiro");
                });

            modelBuilder.Entity("Recebi.Api.Domain.Sindico", b =>
                {
                    b.HasBaseType("Recebi.Api.Domain.Usuario");

                    b.HasDiscriminator().HasValue("Sindico");
                });

            modelBuilder.Entity("Recebi.Api.Domain.Encomenda", b =>
                {
                    b.HasOne("Recebi.Api.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_encomenda_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Recebi.Api.Domain.Historico", b =>
                {
                    b.HasOne("Recebi.Api.Domain.Encomenda", "Encomenda")
                        .WithMany()
                        .HasForeignKey("IdEncomenda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_historico_encomenda");

                    b.HasOne("Recebi.Api.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_historico_usuario");

                    b.Navigation("Encomenda");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
